### ISSUE TITLE
[rGuiLayout] glfwGetVideoMode() fails on Ubuntu platform

### ISSUE THREAD

**Issue by colesnicov** [raylibtech/rtools#11]
Hello. I will try to run rGuiLayout but I get this error:

```
denis@denis-notebook:~/opt/rGuiLayout$ ./rguilayout 
rguilayout: external/glfw/src/monitor.c:441: glfwGetVideoMode: Assertion `monitor != NULL' failed.
Neúspěšně ukončen (SIGABRT) (core dumped [obraz paměti uložen])
```
I have RAYLIB compiled in a temporary folder but it is not installed. However, compiled demo examples from RAYLIB run on. Would you know what to do with it?

I have freshly installed Ubuntu 20.4 LTS..

**Comment by raysan5** [comment]
@colesnicov This issue seems related to GLFW library... published rGuiLayout tool is more than a year old, GLFW library in raylib has been updated several times since then. Also, depending on Linux distro, there could be some issue... I think published version was compiled on Arch Linux.

So, solution to this problem is probably recompiling rGuiLayout with latest raylib and using an Ubuntu distro.

**Comment by colesnicov** [comment]
This is not open source. I won't get to the source. I don't want to pay for a tool that I haven't tried.

**Comment by raysan5** [comment]
@colesnicov I'll try to review this issue for next version, you can wait for it. In the meantime, you can use the web version.

**Comment by colesnicov** [comment]
I'd love to, use the web version, but it's also not very useful. I have a monitor with a resolution of 1280x1024 pixels. Standard office monitor. I can't see the keyboard shortcuts, without them it's useless. Additionally, some keyboard shortcuts are confused with Chrome shortcuts. F1, CTRL + N, ... I'll try to wait ...

[ScreenShot](https://github.com/colesnicov/dump/blob/main/Screenshot_20210601_084720.png)
